apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "tinkerbell.serviceAccountName" . }}
  namespace: {{ include "tinkerbell.namespace" . }}
  labels:
    {{- include "tinkerbell.labels" . | nindent 4 }}
